AWSTemplateFormatVersion: "2010-09-09"
Resources:
  Apartments2:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ApartmentData
      AttributeDefinitions:
        - AttributeName: "ApartmentName"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "ApartmentName"
          KeyType: "HASH"

      ProvisionedThroughput:
        ReadCapacityUnits: "2"
        WriteCapacityUnits: "2"

Outputs:
  TableName:
    Value: !Ref "Apartments2"
    Description: "Name of the newly created DynamoDB table"