AWSTemplateFormatVersion: "2010-09-09"
Resources:
  Apartments:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: DataForApartment
      AttributeDefinitions:
        - AttributeName: "ApartmentName"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "ApartmentName"
          KeyType: "HASH"

      ProvisionedThroughput:
        ReadCapacityUnits: "2"
        WriteCapacityUnits: "2"

Outputs:
  TableName:
    Value: !Ref "Apartments"
    Description: "Name of the newly created DynamoDB table"


# aws cloudformation deploy --template-file Apartments.yaml --stack-name "Apartments"